match $taxpayer isa User; $data_source isa DataSource; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; (declaration: $declaration, source: $data_source) isa uses_data_from; $data_source has identifier "pre-fill"; get;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get; limit 1;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get; limit 1;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; get; limit 1;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $type_of_contract_field (form: $prefill, field: $type_of_contract); $type_of_contract_field isa has_form_field; $type_of_contract_field has identifier == "730/QuadroC/LavoroDipendente/$index/TipoContratto"; $type_of_contract_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $employment_income_field (form: $prefill, field: $employment_income); $employment_income_field isa has_form_field; $employment_income_field has identifier == "730/QuadroC/LavoroDipendente/$index/Reddito"; $employment_income_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_code_field (form: $prefill, field: $bonus_code); $bonus_code_field isa has_form_field; $bonus_code_field has identifier == "730/QuadroC/PremiRisultato/$index/TipoLimite"; $bonus_code_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_ord_tax_field (form: $prefill, field: $amount_performance_bonus_ord_tax); $amount_performance_bonus_ord_tax_field isa has_form_field; $amount_performance_bonus_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoTassazOrdinaria"; $amount_performance_bonus_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_performance_bonus_subst_tax_field (form: $prefill, field: $amount_performance_bonus_subst_tax); $amount_performance_bonus_subst_tax_field isa has_form_field; $amount_performance_bonus_subst_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/ImportoImpostaSostitutiva"; $amount_performance_bonus_subst_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_substitute_tax_field (form: $prefill, field: $withholding_substitute_tax); $withholding_substitute_tax_field isa has_form_field; $withholding_substitute_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/RitenuteImpostaSostitutiva"; $withholding_substitute_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_field (form: $prefill, field: $amount_benefit); $amount_benefit_field isa has_form_field; $amount_benefit_field has identifier == "730/QuadroC/PremiRisultato/$index/Benefit"; $amount_benefit_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_benefit_ord_tax_field (form: $prefill, field: $amount_benefit_ord_tax); $amount_benefit_ord_tax_field isa has_form_field; $amount_benefit_ord_tax_field has identifier == "730/QuadroC/PremiRisultato/$index/BenefitTassOrdinaria"; $amount_benefit_ord_tax_field has index $index; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $number_of_days_field (form: $prefill, field: $number_of_days); $number_of_days_field isa has_form_field; $number_of_days_field has identifier == "730/QuadroC/PeriodoLavoro/GiorniLavoroDipendente"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_irpef_field (form: $prefill, field: $withholding_irpef); $withholding_irpef_field isa has_form_field; $withholding_irpef_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_regional_field (form: $prefill, field: $withholding_regional); $withholding_regional_field isa has_form_field; $withholding_regional_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAddRegionale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_tax_year_field (form: $prefill, field: $withholding_prep_municipal_tax_year); $withholding_prep_municipal_tax_year_field isa has_form_field; $withholding_prep_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_balance_municipal_tax_year_field (form: $prefill, field: $withholding_balance_municipal_tax_year); $withholding_balance_municipal_tax_year_field isa has_form_field; $withholding_balance_municipal_tax_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitSaldoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_current_year_field (form: $prefill, field: $withholding_prep_municipal_current_year); $withholding_prep_municipal_current_year_field isa has_form_field; $withholding_prep_municipal_current_year_field has identifier == "730/QuadroC/RitenuteLavoroDipendente/RitAccAddComAnnoPres"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $first_prepayment_IRPEF_field (form: $prefill, field: $first_prepayment_IRPEF); $first_prepayment_IRPEF_field isa has_form_field; $first_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/PrimaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $second_prepayment_IRPEF_field (form: $prefill, field: $second_prepayment_IRPEF); $second_prepayment_IRPEF_field isa has_form_field; $second_prepayment_IRPEF_field has identifier == "730/QuadroF/AccontiIrpef/SecondaRataAccontoIrpef"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $withholding_prep_municipal_field (form: $prefill, field: $withholding_prep_municipal); $withholding_prep_municipal_field isa has_form_field; $withholding_prep_municipal_field has identifier == "730/QuadroF/AccontiIrpef/AccontoAddComunale"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amount_bonus_irpef_paid_field (form: $prefill, field: $amount_bonus_irpef_paid); $amount_bonus_irpef_paid_field isa has_form_field; $amount_bonus_irpef_paid_field has identifier == "730/QuadroC/BonusIrpef/BonusErogato"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_exemption_field (form: $prefill, field: $bonus_irpef_exemption); $bonus_irpef_exemption_field isa has_form_field; $bonus_irpef_exemption_field has identifier == "730/QuadroC/BonusIrpef/EsenzioneRicercatori"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_quota_tfr_field (form: $prefill, field: $bonus_irpef_quota_tfr); $bonus_irpef_quota_tfr_field isa has_form_field; $bonus_irpef_quota_tfr_field has identifier == "730/QuadroC/BonusIrpef/QuotaTfr"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $bonus_irpef_code_field (form: $prefill, field: $bonus_irpef_code); $bonus_irpef_code_field isa has_form_field; $bonus_irpef_code_field has identifier == "730/QuadroC/BonusIrpef/CodiceBonus"; get ;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $reimbursement_to_employer isa ReimbursementToEmployer; (expense_payer: $taxpayer, expense: $reimbursement_to_employer) isa bears; $reimbursement_to_employer isa ReimbursementToEmployer; (expense_payer: $taxpayer, expense: $reimbursement_to_employer) isa bears; get;
match $taxpayer isa User; (filer: $taxpayer, declaration: $declaration) isa files_tax_declaration; $prefill isa FormDataSource; $prefill has identifier == "pre-fill"; (declaration: $declaration, source: $prefill) isa uses_data_from; $amounts_unduly_taxed isa AmountsUndulyTaxedUnderEmploymentIncome; (expense_payer: $taxpayer, expense: $amounts_unduly_taxed) isa bears; get;